/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservadevuelos.vistas;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Sebastian
 */
public class VistaAgregarCiudades extends javax.swing.JInternalFrame {
    
    
    DefaultTableModel model_1;
    
    //FUTURO METODO PARA CARGAR LOS DATOS EN LA TABLA.
    public void cargarDatos(){

        String [] titulos = {"Id de Ciudad", "Nombre", "Pais", "Vigencia"};

        model_1 = new DefaultTableModel(null, titulos);
    
        jTable1.setModel(model_1);
                 
    }

       
       
            
    public VistaAgregarCiudades() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtPais = new javax.swing.JTextField();
        txtNombreCiudad = new javax.swing.JTextField();
        rbVigencia = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new rsbuttom.RSButtonMetro();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(790, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 780, 400));
        getContentPane().add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 170, -1));

        txtNombreCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 170, -1));

        rbVigencia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbVigencia.setText("Vigencia");
        rbVigencia.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rbVigencia.setIconTextGap(10);
        getContentPane().add(rbVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Ciudad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 50, -1));

        btnGuardar.setText("GUARDAR");
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Separator Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("AGREGAR NUEVAS CIUDADES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 600, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Pais");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCiudadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbVigencia;
    private javax.swing.JTextField txtNombreCiudad;
    private javax.swing.JTextField txtPais;
    // End of variables declaration//GEN-END:variables
}
