/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservadevuelos.vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import reservadevuelos.modelo.Asiento;
import reservadevuelos.modelo.AsientoData;
import reservadevuelos.modelo.Conexion;

/**
 *
 * @author Sebastian
 */
public class VistaModificarAsiento extends javax.swing.JInternalFrame {

    private Connection connection = null;
    private Conexion conexion;
    
    public VistaModificarAsiento() {
        initComponents();
        
        try {
             conexion = new Conexion("jdbc:mysql://localhost/reserva_de_vuelos", "root", "");
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(VistaAltaVuelo.class.getName()).log(Level.SEVERE, null, ex);
         }
        jComboBoxModIdAsiento.removeAllItems();
        jComboBoxModIdVuelo.removeAllItems();
        
        try {
            connection = conexion.getConexion();
            String sql = " SELECT * FROM vuelo ";
            String sql2 = " SELECT * FROM asiento ";
            PreparedStatement statement = connection.prepareStatement(sql);
            
            ResultSet resultSet = statement.executeQuery();
            while(resultSet.next()){
                String id = String.valueOf(resultSet.getInt("idVuelo"));
                jComboBoxModIdVuelo.addItem(id);                
            }
            statement.close();
            PreparedStatement statement2 = connection.prepareStatement(sql2);
            ResultSet resultSet2 = statement2.executeQuery();
            while(resultSet2.next()){
                String idA = String.valueOf(resultSet2.getInt("idAsiento"));
                jComboBoxModIdAsiento.addItem(idA);                
            }
            
            statement2.close();
            
        } catch (SQLException ex) {
            System.out.println("Error al obtener la conexion");
        }
        jLabelCampoO1.setVisible(false);
        jLabelCampoO2.setVisible(false);
        
    }
    public void obtenerIdTabla(int id){
        jComboBoxModIdAsiento.setSelectedIndex(id);
    }
    public void camposObligatorios(){
           if (jTextFieldModNumero.getText().equals("")) {
               jLabelCampoO1.setVisible(true);
               
           }else{
               jLabelCampoO1.setVisible(false);
               
           }
           if (jTextFieldModPrecio.getText().equals("")) {
               jLabelCampoO2.setVisible(true);
               
           }else{
               jLabelCampoO2.setVisible(false);
               
           }
 
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxModIdAsiento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxModIdVuelo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxModLetra = new javax.swing.JComboBox<>();
        jTextFieldModNumero = new javax.swing.JTextField();
        jRadioButtonModDisp = new javax.swing.JRadioButton();
        jTextFieldModPrecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelCampoO1 = new javax.swing.JLabel();
        jLabelCampoO2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(395, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MODIFICAR ASIENTO");

        jLabel2.setText("Id. Asiento");

        jComboBoxModIdAsiento.setMaximumRowCount(50);
        jComboBoxModIdAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModIdAsientoActionPerformed(evt);
            }
        });

        jLabel3.setText("Id. Vuelo");

        jComboBoxModIdVuelo.setMaximumRowCount(50);

        jLabel4.setText("Letra");

        jLabel5.setText("Número");

        jLabel6.setText("Disponible");

        jLabel7.setText("Precio");

        jComboBoxModLetra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K" }));

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelCampoO1.setText("Campo obligatorio");

        jLabelCampoO2.setText("Campo obligatorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldModNumero)
                            .addComponent(jTextFieldModPrecio)
                            .addComponent(jComboBoxModIdVuelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxModLetra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonModDisp)
                                    .addComponent(jComboBoxModIdAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCampoO1)
                            .addComponent(jLabelCampoO2))
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(55, 55, 55)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxModIdAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxModIdVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxModLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldModNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCampoO1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButtonModDisp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldModPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCampoO2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        camposObligatorios();
        if (!jTextFieldModNumero.getText().equals("") && !jTextFieldModPrecio.getText().equals("")) {
            AsientoData ad = new AsientoData(conexion);
            Asiento unAsiento;
            int idA = Integer.parseInt(jComboBoxModIdAsiento.getSelectedItem().toString());
            int idV = Integer.parseInt(jComboBoxModIdVuelo.getSelectedItem().toString());
            String letra = jComboBoxModLetra.getSelectedItem().toString();
            int numero = Integer.parseInt(jTextFieldModNumero.getText());
            boolean disp = jRadioButtonModDisp.isSelected();
            double precio = Double.parseDouble(jTextFieldModPrecio.getText());
            unAsiento = new Asiento(idV, letra, numero, disp, precio);
            ad.modificarAsiento(unAsiento,idA);
            Inicio.escritorio.updateUI();
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(null, "Faltan campos obligatorios");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxModIdAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModIdAsientoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxModIdAsientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxModIdAsiento;
    private javax.swing.JComboBox<String> jComboBoxModIdVuelo;
    private javax.swing.JComboBox<String> jComboBoxModLetra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCampoO1;
    private javax.swing.JLabel jLabelCampoO2;
    private javax.swing.JRadioButton jRadioButtonModDisp;
    private javax.swing.JTextField jTextFieldModNumero;
    private javax.swing.JTextField jTextFieldModPrecio;
    // End of variables declaration//GEN-END:variables
}
