/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservadevuelos.vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import reservadevuelos.modelo.Ciudad;
import reservadevuelos.modelo.CiudadData;
import reservadevuelos.modelo.Conexion;
import reservadevuelos.modelo.Vuelo;
import reservadevuelos.modelo.VueloData;

/**
 *
 * @author Usuario
 */
public class VistaConsultaVuelo extends javax.swing.JInternalFrame {
    VueloData vd;
    private DefaultTableModel modelo; 
    private Connection connection = null;
    private Conexion conexion;
    
    /**
     * Creates new form VistaBajaVuelo
     */
    public VistaConsultaVuelo() {
         initComponents();
         
         try {
             conexion = new Conexion("jdbc:mysql://localhost/reserva_de_vuelos", "root", "");
             
             modelo=new DefaultTableModel();
             
             vd= new VueloData(conexion);
             mostrar(vd.cantVuelos());             
                         
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(VistaConsultaVuelo.class.getName()).log(Level.SEVERE, null, ex);
         }
        
         //carga los combo box con las ciudades que trae desde la bd 
        this.jComboBoxOrigen.removeAllItems();
        this.jComboBoxDestino.removeAllItems();
        try {
            connection = conexion.getConexion();
            String sql = " SELECT * FROM ciudad WHERE vigencia = 1";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery();
            while(resultSet.next()){
                this.jComboBoxOrigen.addItem(resultSet.getString("nbreCiudad"));
                this.jComboBoxDestino.addItem(resultSet.getString("nbreCiudad"));
            }
            
        } catch (SQLException ex) {
            System.out.println("Error al abrir al obtener la conexion");
        }
               
    }
     
    public void mostrar(List<Vuelo> vuelos){        
        //VueloData vd= new VueloData(conexion);
        //List<Vuelo> vuelos = new ArrayList<>();
        //vuelos= vd.cantVuelos();
        modelo = (DefaultTableModel) tVuelos.getModel();
        borrarFilas();
        Object[] fila= new Object [modelo.getColumnCount()]; 
        for (int i=0;i < vuelos.size();i++){
            fila[0]=vuelos.get(i).getCiudadOrigen().getNombreCiudad();
            fila[1]=vuelos.get(i).getCiudadDestino().getNombreCiudad();            
            fila[2]=vuelos.get(i).getAerolinea();
            fila[3]=vuelos.get(i).getAeronave();
            fila[4]=vuelos.get(i).getFechaSalida();
            fila[5]=vuelos.get(i).getFechaLlegada();
            fila[6]=vuelos.get(i).getEstadoVuelo();
            fila[7]=vuelos.get(i).getIdVuelo();
            modelo.addRow(fila);
        }
        
       tVuelos.setModel(modelo);
                
    }
    
    public void borrarFilas(){
        int a =modelo.getRowCount()-1;
        for(int i=a;i>=0;i--){
                modelo.removeRow(i );
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaVuelos = new javax.swing.JScrollPane();
        tVuelos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBbuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFecha = new com.toedter.calendar.JDateChooser();

        tVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ciudad Origen", "Ciudad Destino", "Aerolinea", "Aeronave", "Fecha Salida", "Fecha Llegada", "Estado de Vuelo", "Codigo de Vuelo"
            }
        ));
        tablaVuelos.setViewportView(tVuelos);

        jLabel1.setText("Consultar Vuelos");

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Origen");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Avion_50x50.png"))); // NOI18N

        jComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Destino");

        jLabel5.setText("Fecha Salida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jBbuscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(276, 276, 276)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(tablaVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addComponent(jBbuscar))
                        .addGap(41, 41, 41)
                        .addComponent(tablaVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        List<Vuelo> vueloEn= new ArrayList<Vuelo>(); 
        CiudadData cd= new CiudadData(conexion);
        Ciudad c= new Ciudad();
        c= cd.obtenerCiudad((String)jComboBoxOrigen.getSelectedItem());
        Ciudad c2= new Ciudad();
        c2= cd.obtenerCiudad((String)jComboBoxDestino.getSelectedItem());  
        LocalDate fecha;
        fecha=jFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        vueloEn=vd.vueloEntre(c, c2, fecha);
        mostrar(vueloEn);
    }//GEN-LAST:event_jBbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxOrigen;
    private com.toedter.calendar.JDateChooser jFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTable tVuelos;
    private javax.swing.JScrollPane tablaVuelos;
    // End of variables declaration//GEN-END:variables
}
