/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservadevuelos.vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import reservadevuelos.modelo.Ciudad;
import reservadevuelos.modelo.CiudadData;
import reservadevuelos.modelo.Conexion;
import reservadevuelos.modelo.Vuelo;
import reservadevuelos.modelo.VueloData;

/**
 *
 * @author Usuario
 */
public class VistaBajaVuelo extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo; 
    private Connection connection = null;
    private Conexion conexion;
    
    /**
     * Creates new form VistaBajaVuelo
     */
    public VistaBajaVuelo() {
        initComponents();
         try {
             conexion = new Conexion("jdbc:mysql://localhost/reserva_de_vuelos", "root", "");
             
             modelo=new DefaultTableModel();
             mostrar();
                         
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(VistaAltaVuelo.class.getName()).log(Level.SEVERE, null, ex);
         }
        
       
        
    }
     
    public void mostrar(){        
        VueloData vd= new VueloData(conexion);
        List<Vuelo> vuelos = new ArrayList<>();
        vuelos= vd.cantVuelos();
        modelo = (DefaultTableModel) tVuelos.getModel();
        borrarFilas();
        Object[] fila= new Object [modelo.getColumnCount()]; 
        for (int i=0;i < vuelos.size();i++){
            
            fila[0]=vuelos.get(i).getCiudadOrigen().getNombreCiudad();
            fila[1]=vuelos.get(i).getCiudadDestino().getNombreCiudad();            
            fila[2]=vuelos.get(i).getAerolinea();
            fila[3]=vuelos.get(i).getAeronave();
            fila[4]=vuelos.get(i).getFechaSalida();
            fila[5]=vuelos.get(i).getFechaLlegada();
            fila[6]=vuelos.get(i).getEstadoVuelo();
            fila[7]=vuelos.get(i).getIdVuelo();
            modelo.addRow(fila);
        }
        
       tVuelos.setModel(modelo);
                
    }
    
    public void borrarFilas(){
        int a =modelo.getRowCount()-1;
        for(int i=a;i>=0;i--){
                modelo.removeRow(i );
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaVuelos = new javax.swing.JScrollPane();
        tVuelos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextCodigo = new javax.swing.JTextField();

        tVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ciudad Origen", "Ciudad Destino", "Aerolinea", "Aeronave", "Fecha Salida", "Fecha Llegada", "Estado de Vuelo", "Codigo de Vuelo"
            }
        ));
        tablaVuelos.setViewportView(tVuelos);

        jLabel1.setText("Vuelos");

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(288, 288, 288))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(tablaVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VueloData vd= new VueloData(conexion);
        vd.bajaVuelo( Integer.parseInt(jTextCodigo.getText()));
        jTextCodigo.setText(null);
        modelo.setRowCount(0);
        this.mostrar();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTable tVuelos;
    private javax.swing.JScrollPane tablaVuelos;
    // End of variables declaration//GEN-END:variables
}
