/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservadevuelos.vistas;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import reservadevuelos.modelo.Asiento;
import reservadevuelos.modelo.AsientoData;
import reservadevuelos.modelo.Conexion;

/**
 *
 * @author Sebastian
 */
public class VistaGestionAsiento extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo; 
    private Connection connection = null;
    private Conexion conexion;
    
    public VistaGestionAsiento() {
        initComponents();
        try {
             conexion = new Conexion("jdbc:mysql://localhost/reserva_de_vuelos", "root", "");
             
             modelo = new DefaultTableModel();
             mostrar();
                         
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(VistaAltaVuelo.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    public void mostrar(){        
        AsientoData ad = new AsientoData(conexion);
        List<Asiento> asientos = new ArrayList<>();
        asientos = ad.obtenerAsientos();
        modelo = (DefaultTableModel) jTableAsientos.getModel();
        borrarFilas();
        Object[] fila = new Object [modelo.getColumnCount()]; 
        for (int i = 0; i < asientos.size(); i++){
            
            fila[0] = asientos.get(i).getIdAsiento();
            fila[1]=asientos.get(i).getIdVuelo();
            fila[2]=asientos.get(i).getLetra();
            fila[3]=asientos.get(i).getNumero();
            fila[4]=asientos.get(i).getPrecioAsiento();

            modelo.addRow(fila);
        }
        
       jTableAsientos.setModel(modelo);
                
    }
    public void borrarFilas(){
        int a = modelo.getRowCount()-1;
        for(int i = a; i >= 0; i--){
                modelo.removeRow(i);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAsientos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(395, 450));

        jTableAsientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id. Asiento", "Id. Vuelo", "Letra", "Número", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAsientos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableAsientos.setName("Asientos"); // NOI18N
        jTableAsientos.setOpaque(false);
        jTableAsientos.getTableHeader().setResizingAllowed(false);
        jTableAsientos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableAsientos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion de Asientos");

        jButtonModificar.setText("MODIFICAR");

        jButtonEliminar.setText("ELIMINAR");

        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonSalir))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAsientos;
    // End of variables declaration//GEN-END:variables
}
