/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservadevuelos.vistas;

import java.sql.Connection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import reservadevuelos.modelo.Ciudad;
import reservadevuelos.modelo.CiudadData;
import reservadevuelos.modelo.Conexion;

/**
 *
 * @author Usuario
 */
public class VistaCiudadGestion extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo; 
    private Connection connection = null;
    private Conexion conexion;
    private CiudadData cd;
    private Ciudad ciudad1;
    
    /**
     * Creates new form VistaCiudadGestion
     */
    public VistaCiudadGestion() {
        initComponents();
        deshabilitarCampos();
         try {
            conexion = new Conexion("jdbc:mysql://localhost/reserva_de_vuelos", "root", "");
            cd=new CiudadData(conexion);
            modelo=new DefaultTableModel();
            mostrar(cd.obtenerCiudades());             
                         
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(VistaConsultaVuelo.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    //carga los datos de la lista en la tabla
     private void mostrar(List <Ciudad> ciudades){        
        modelo = (DefaultTableModel) jTableCiudades.getModel();
        borrarFilas();
        Object[] fila= new Object [modelo.getColumnCount()]; 
        for (int i=0;i < ciudades.size();i++){
            fila[0]=ciudades.get(i).getIdCiudad();
            fila[1]=ciudades.get(i).getNombreCiudad();            
            fila[2]=ciudades.get(i).getPais();
            if (ciudades.get(i).getVigencia()){
            fila[3]="Vigente";}
            else{
                fila[3]="Fuera de servicio";
            }
            modelo.addRow(fila);
        }
        
       jTableCiudades.setModel(modelo);
    }
    
    // borra las filas de la tabla
     public void borrarFilas(){
        int a =modelo.getRowCount()-1;
        for(int i=a;i>=0;i--){
                modelo.removeRow(i );
            }
    }
    
    //deshabilita todos los campos de la vista
     private void deshabilitarCampos(){
         jTextId.setEnabled(false);
         jTextNombreCiudad.setEnabled(false);
         jTextPais.setEnabled(false);
         jRBVigencia.setEnabled(false);
       }
    
     //habilita todos los campos de la vista
     private void habilitarCampos(){
         jTextId.setEnabled(true);
         jTextNombreCiudad.setEnabled(true);
         jTextPais.setEnabled(true);
         jRBVigencia.setEnabled(true);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCiudades = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextId = new javax.swing.JTextField();
        jTextNombreCiudad = new javax.swing.JTextField();
        jTextPais = new javax.swing.JTextField();
        jRBVigencia = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Mapa_50x50_azul.png"))); // NOI18N

        jLabel2.setText("Gestion de Ciudades");

        jTableCiudades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Pais", "Vigencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCiudades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCiudadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCiudades);

        jLabel3.setText("Codigo");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPaisActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("Pais");

        jLabel6.setText("Vigencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextNombreCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jTextId))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(55, 55, 55)
                                .addComponent(jRBVigencia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(45, 45, 45)
                                .addComponent(jTextPais, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2))
                    .addComponent(jLabel2))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextPais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6))
                    .addComponent(jRBVigencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPaisActionPerformed

    private void jTableCiudadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCiudadesMouseClicked
        habilitarCampos();
        jRBVigencia.setSelected(false);
        int selection=jTableCiudades.rowAtPoint(evt.getPoint());
        jTextId.setText(String.valueOf(jTableCiudades.getValueAt(selection, 0)));
        jTextNombreCiudad.setText(String.valueOf(jTableCiudades.getValueAt(selection,1)));
        jTextPais.setText(String.valueOf(jTableCiudades.getValueAt(selection,2)));
        if (jTableCiudades.getValueAt(selection,3)=="Vigente"){
            jRBVigencia.setSelected(true);
        }
        jTextId.setEditable(false);
    }//GEN-LAST:event_jTableCiudadesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar el asiento?") == JOptionPane.YES_OPTION){
            cd= new CiudadData(conexion);
            ciudad1=new Ciudad(jTextNombreCiudad.getText(),jTextPais.getText(),jRBVigencia.isSelected());
            ciudad1.setIdCiudad(Integer.parseInt(jTextId.getText()));
            cd.modifCiudad(ciudad1);
            mostrar(cd.obtenerCiudades());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Seguro que desea modificar la ciudad?") == JOptionPane.YES_OPTION){
             cd= new CiudadData(conexion);
             cd.bajaCiudad(Integer.parseInt(jTextId.getText()));
             mostrar(cd.obtenerCiudades());
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRBVigencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCiudades;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextNombreCiudad;
    private javax.swing.JTextField jTextPais;
    // End of variables declaration//GEN-END:variables
}
